### ISSUE TITLE
Checklist for Factoids - Other: 

### ISSUE THREAD

**Issue by lunadine** [usaybia/usaybia-data#188]
### Please describe the issue

@nathangibson @MalindaT 
You are aware of all of this, but it also helps me to get an idea of what needs to be done before the final versions of the files, So I created here a checklist for things that need to be updated in our factoid files, particularly in the headers;
feel free to add other things to this issue:

Headers

- [ ] Information contained in the `<TEI>` field is not identical in all files
- [ ] NL+MT should always make sure that the field   `<editor role="creator">` **as well as** `<resp>Data entry and encoding by</resp>` in the header contains the correct name  
- [ ]  `<idno type="URI">` needs to be the currently encoded chapter!
- [ ] @nathangibson  `<date>` info has to be added
- [ ]  `<revisionDesc>` is empty

Others
- [ ] do we need to watch out for line breaks in our factoid files? standardize these?
- [ ] watch out for the correct subtype in older files
- [ ] proof read `<rs>` tag and correct use of work URI's in older factoid files

A question regarding the field
```
<category xml:id="calculated">
                        <catDesc> Used to denote a date calculated by the editor from a regnal year
                            given in the text. </catDesc>
```
-> it is not only regnal years we calculate, right?

**Comment by nathangibson** [comment]
@lunadine Thank you for these. As we get closer I might break these into individual issues. 

Just to document regarding the `#calculated` category: We don't need to worry about this description unless we are using `#calculated` as an attribute value. If we do, then as you said, we should adapt the description.
